image: atlassian/default-image:3

pipelines:
  branches:
    salto_deployment_after_*:
      - step:
          name: 'Run Salesforce Validation'
          script:
            - echo "Downloading and installing Salto CLI.."
            - curl https://cli.salto.io/release/1/linux-x64.tar.gz --output linux-x64.tar.gz
            - tar xvzf linux-x64.tar.gz
            - echo "Running Salesforce validation.."
            - ./salto-cloud deployment validate -b $BITBUCKET_BRANCH -C 'salesforce.client.deploy.testLevel=RunLocalTests'
