trigger:
- salto/after/env/*

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    echo "Downloading and installing Salto CLI.."
    curl https://cli.salto.io/release/1/linux-x64.tar.gz --output linux-x64.tar.gz
    tar xvzf linux-x64.tar.gz
    echo "Checking Deployment Plan.."
    ./salto-cloud deployment preview -b $SOURCE_BRANCH
  displayName: 'Check Deployment Plan'
  env:
    SALTO_API_TOKEN: $(SALTO_API_TOKEN)
    SOURCE_BRANCH: $(Build.SourceBranchName)
    