trigger:
- salto_deployment_after_*

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    echo "Downloading and installing Salto CLI.."
    curl https://cli.salto.io/release/1/linux-x64.tar.gz --output linux-x64.tar.gz
    tar xvzf linux-x64.tar.gz
    echo "Running Salesforce validation.."
    ./salto-cloud deployment validate -b $SOURCE_BRANCH -C 'salesforce.client.deploy.testLevel=RunLocalTests'
  displayName: 'Run Salesforce Validation'
  env:
    SALTO_API_TOKEN: $(SALTO_API_TOKEN)
    SOURCE_BRANCH: $(Build.SourceBranchName)
    