stages:
  - Check Deployment Plan

variables:
  SALTO_API_TOKEN: "SALTO_API_TOKEN_HERE"

run-salesforce-validation:
  stage: Check Deployment Plan
  script:
    - echo "Downloading and installing Salto CLI.."
    - curl https://cli.salto.io/release/1/linux-x64.tar.gz --output linux-x64.tar.gz
    - tar xvzf linux-x64.tar.gz
    - echo "Checking Deployment Plan.."
    - ./salto-cloud deployment preview -b $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_REF_NAME =~ /^salto\/deployments\/after\/.*/'
      allow_failure: false
