stages:
  - Run Salesforce Validation

variables:
  SALTO_API_TOKEN: "SALTO_API_TOKEN_HERE"

run-salesforce-validation:
  stage: Run Salesforce Validation
  script:
    - echo "Downloading and installing Salto CLI.."
    - curl https://salto-saas-cli.s3.us-east-2.amazonaws.com/release/1.0.0/linux-x64.tar.gz --output linux-x64.tar.gz
    - tar xvzf linux-x64.tar.gz
    - echo "Running Salesforce validation.."
    - export API_TOKEN=$SALTO_API_TOKEN
    - ./salto-cloud deployment validate -b $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME -C 'salesforce.client.deploy.testLevel=RunLocalTests'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      allow_failure: false
