name: Validate
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  Validate:
    if: startsWith(github.event.pull_request.head.ref, 'salto/env/')
    runs-on: ubuntu-latest
    steps:
      - name: Install Salto CLI
        run: |
          curl https://cli.salto.io/release/1/linux-x64.tar.gz --output linux-x64.tar.gz
          tar xvzf linux-x64.tar.gz
        
      - name: Run Deploy Validation
        run: |
          ./salto-cloud deployment validate -b ${GITHUB_HEAD_REF} -C 'salesforce.client.deploy.testLevel=RunLocalTests'
        env: 
          SALTO_API_TOKEN: ${{ secrets.SALTO_API_TOKEN }}
